In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [53]:
df=pd.read_csv("customer_data.csv")
df

,Customer ID,Age,Gender,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No,No,36.0,Cash,Weekly
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No,No,18.0,Cash,Monthly
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No,No,25.0,Cash,Annually
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,56.0,Arkansas,M,Green,Winter,3.4,Yes,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,53.0,Iowa,M,Gold,Spring,3.4,No,No,31.0,Debit Card,Weekly
5047,3572,70,Female,27.0,North Dakota,M,White,Summer,3.2,No,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,52.0,Maryland,L,Gold,Summer,4.6,No,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,71.0,Maine,M,Cyan,Summer,NaN,No,No,5.0,Bank Transfer,Every 3 Months

In [54]:
df.head()

,Customer ID,Age,Gender,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No,No,36.0,Cash,Weekly
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No,No,18.0,Cash,Monthly
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No,No,25.0,Cash,Annually
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No,No,17.0,Credit Card,Weekly

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             5050 non-null   int64
 1   Age                     5050 non-null   int64
 2   Gender                  5050 non-null   object
 3   Purchase Amount (USD)   4492 non-null   float64
 4   Location                5050 non-null   object
 5   Size                    4676 non-null   object
 6   Color                   5050 non-null   object
 7   Season                  5050 non-null   object
 8   Review Rating           4448 non-null   float64
 9   Subscription Status     5050 non-null   object
 10  Discount Applied        5048 non-null   object
 11  Previous Purchases      4502 non-null   float64
 12  Payment Method          5050 non-null   object
 13  Frequency of Purchases  5050 non-null   object
dtypes: float64(3), int64(2), object(9)
memory usage: 552.5+ KB

In [56]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4492.000000,4448.000000,4502.000000
mean,2519.570891,44.150495,144.805203,3.668278,25.221901
std,1470.402964,15.282328,275.644944,0.865436,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [57]:
df.shape

(5050, 14)

In [58]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Purchase Amount (USD)', 'Location',
       'Size', 'Color', 'Season', 'Review Rating', 'Subscription Status',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [59]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Purchase Amount (USD)     558
Location                    0
Size                      374
Color                       0
Season                      0
Review Rating             602
Subscription Status         0
Discount Applied            2
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [60]:
df.duplicated().sum()

np.int64(50)

In [61]:
df.drop_duplicates(inplace=True)
df

,Customer ID,Age,Gender,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No,No,36.0,Cash,Weekly
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No,No,18.0,Cash,Monthly
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No,No,25.0,Cash,Annually
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No,No,17.0,Credit Card,Weekly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,56.0,Arkansas,M,Green,Winter,3.4,Yes,Yes,32.0,Bank Transfer,Monthly
5046,3466,19,Female,53.0,Iowa,M,Gold,Spring,3.4,No,No,31.0,Debit Card,Weekly
5047,3572,70,Female,27.0,North Dakota,M,White,Summer,3.2,No,No,15.0,Bank Transfer,Every 3 Months
5048,3195,43,Female,52.0,Maryland,L,Gold,Summer,4.6,No,No,10.0,Credit Card,Bi-Weekly
5049,1832,62,Male,71.0,Maine,M,Cyan,Summer,NaN,No,No,5.0,Bank Transfer,Every 3 Months

In [62]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={"purchase_amount_(usd)":"purchase_amount"})
df.columns

Index(['customer_id', 'age', 'gender', 'purchase_amount', 'location', 'size',
       'color', 'season', 'review_rating', 'subscription_status',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [63]:
bins = [0,20,35,50,100]
labels = ["Teen","Young Adult","Adult","Senior"]
df["age_group"]=pd.cut(df["age"],bins=bins,labels=labels)

,customer_id,age,gender,purchase_amount,location,size,color,season,review_rating,subscription_status,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group
0,2701,22,Female,68.0,California,XL,Olive,Winter,3.2,No,No,36.0,Cash,Weekly,Young Adult
1,521,51,Male,84.0,South Carolina,M,White,Spring,3.9,Yes,Yes,20.0,Debit Card,Quarterly,Senior
2,3157,18,Female,50.0,Montana,M,Black,Winter,3.1,No,No,18.0,Cash,Monthly,Teen
3,1687,22,Male,75.0,Illinois,L,Red,Fall,4.2,No,No,25.0,Cash,Annually,Young Adult
4,2929,40,Female,80.0,Alabama,L,Yellow,Spring,3.6,No,No,17.0,Credit Card,Weekly,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5045,913,24,Male,56.0,Arkansas,M,Green,Winter,3.4,Yes,Yes,32.0,Bank Transfer,Monthly,Young Adult
5046,3466,19,Female,53.0,Iowa,M,Gold,Spring,3.4,No,No,31.0,Debit Card,Weekly,Teen
5047,3572,70,Female,27.0,North Dakota,M,White,Summer,3.2,No,No,15.0,Bank Transfer,Every 3 Months,Senior
5048,3195,43,Female,52.0,Maryland,L,Gold,Summer,4.6,No,No,10.0,Credit Card,Bi-Weekly,Adult
5049,1832,62,Male,71.0,Maine,M,Cyan,Summer,NaN,No,No,5.0,Bank Transfer,Every 3 Months,Senior

In [64]:
def Purchase_category(x):
    if x<30:
        return "Low"
    elif x<70:
        return "Medium"
    else:
        return "High"

df["purchase_category"]=df["purchase_amount"].apply(Purchase_category)

In [66]:
df.to_csv("retail_data_cleaned.csv",index=False)